FROM node:20-slim
WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --frozen-lockfile --network-timeout 600000
COPY . ./

EXPOSE 3000
ENTRYPOINT ["yarn", "start"]
