[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = [
  "cd backend && yarn install",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd backend && yarn build",
  "cd frontend && yarn build"
]

[start]
cmd = "cd backend && yarn start"


