import { DayOfWeek, DayPreference, Icon, Level, TaskType, TimePreference } from "@prisma/client";
import * as systemBadge from "../constants/systemBadges";

export const systemBadges = [
  {
    name: systemBadge.LOGIN,
    description: "Logged in for several days in a row",
    is_active: true,
    icon: Icon.FOUR_STAR,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    description: "Completed 3+ optional tasks for several weeks",
    is_active: true,
    icon: Icon.FLOWER,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    description: "Completed all mandatory tasks for several weeks",
    is_active: true,
    icon: Icon.PENCIL,
  },
  {
    name: systemBadge.MONEY_EARNED,
    description: "Total marillac buck earnings",
    is_active: true,
    icon: Icon.MONEY,
  },
  {
    name: systemBadge.PR_LEADER,
    description: "Accumulation of other badges & levels",
    is_active: true,
    icon: Icon.DIAMOND,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    description: "Set and completed all individual goals for several weeks",
    is_active: true,
    icon: Icon.GEMSTONE,
  },
  {
    name: systemBadge.FIRST_GOAL,
    description: "Set and complete first individual goal",
    is_active: true,
    icon: Icon.FIVE_STAR, 
  },
  {
    name: systemBadge.JACK_OF_ALL_TRADES,
    description: "Total tried tasks",
    is_active: true,
    icon: Icon.TOOL,
  },
];

export const badgeLevels = [
  {
    name: systemBadge.LOGIN,
    level: Level.NOVICE,
    value: 2,
    benchmark: 1,
  },
  {
    name: systemBadge.LOGIN,
    level: Level.BRONZE,
    value: 5,
    benchmark: 7,
  },
  {
    name: systemBadge.LOGIN,
    level: Level.SILVER,
    value: 10,
    benchmark: 30,
  },
  {
    name: systemBadge.LOGIN,
    level: Level.GOLD,
    value: 20,
    benchmark: 90,
  },
  {
    name: systemBadge.LOGIN,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 180,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    level: Level.NOVICE,
    value: 2,
    benchmark: 1,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    level: Level.BRONZE,
    value: 5,
    benchmark: 4,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    level: Level.SILVER,
    value: 10,
    benchmark: 8,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    level: Level.GOLD,
    value: 20,
    benchmark: 12,
  },
  {
    name: systemBadge.PERFECT_SCORE_OPTIONAL,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 16,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    level: Level.NOVICE,
    value: 2,
    benchmark: 1,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    level: Level.BRONZE,
    value: 5,
    benchmark: 4,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    level: Level.SILVER,
    value: 10,
    benchmark: 8,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    level: Level.GOLD,
    value: 20,
    benchmark: 12,
  },
  {
    name: systemBadge.PERFECT_SCORE_REQUIRED,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 16,
  },
  {
    name: systemBadge.MONEY_EARNED,
    level: Level.NOVICE,
    value: 2,
    benchmark: 100,
  },
  {
    name: systemBadge.MONEY_EARNED,
    level: Level.BRONZE,
    value: 5,
    benchmark: 500,
  },
  {
    name: systemBadge.MONEY_EARNED,
    level: Level.SILVER,
    value: 10,
    benchmark: 1000,
  },
  {
    name: systemBadge.MONEY_EARNED,
    level: Level.GOLD,
    value: 20,
    benchmark: 4000,
  },
  {
    name: systemBadge.MONEY_EARNED,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 8000,
  },
  {
    name: systemBadge.PR_LEADER,
    level: Level.NOVICE,
    value: 2,
    benchmark: 4,
  },
  {
    name: systemBadge.PR_LEADER,
    level: Level.BRONZE,
    value: 5,
    benchmark: 4,
  },
  {
    name: systemBadge.PR_LEADER,
    level: Level.SILVER,
    value: 10,
    benchmark: 4,
  },
  {
    name: systemBadge.PR_LEADER,
    level: Level.GOLD,
    value: 20,
    benchmark: 4,
  },
  {
    name: systemBadge.PR_LEADER,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 4,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    level: Level.NOVICE,
    value: 2,
    benchmark: 1,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    level: Level.BRONZE,
    value: 5,
    benchmark: 4,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    level: Level.SILVER,
    value: 10,
    benchmark: 8,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    level: Level.GOLD,
    value: 20,
    benchmark: 12,
  },
  {
    name: systemBadge.INDIVIDUAL_GOAL,
    level: Level.DIAMOND,
    value: 40,
    benchmark: 16,
  },
  {
    name: systemBadge.FIRST_GOAL,
    level: Level.NOVICE,
    value: 2,
    benchmark: 1,
  },
  {
    name: systemBadge.JACK_OF_ALL_TRADES,
    level: Level.SILVER,
    value: 10,
    benchmark: 10,
  },
]

export const tasks = [
  {
    name: "Weekly Review with CM",
    type: TaskType.REQUIRED,
    value: 5,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Skill Session with PM",
    type: TaskType.REQUIRED,
    value: 5,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Housing Plan",
    type: TaskType.REQUIRED,
    value: 10,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Weekly House Meeting",
    type: TaskType.OPTIONAL,
    value: 5,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Curfew",
    type: TaskType.OPTIONAL,
    value: 5,
    day_preference: DayPreference.DAILY,
    days: [],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Chore",
    type: TaskType.OPTIONAL,
    value: 10,
    day_preference: DayPreference.DAILY,
    days: [],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Laundry",
    type: TaskType.OPTIONAL,
    value: 2,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Bedroom Inspection",
    type: TaskType.OPTIONAL,
    value: 5,
    day_preference: DayPreference.EVERY_SELECTED_DAYS,
    days: [DayOfWeek.MONDAY, DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Speaker's Corner",
    type: TaskType.OPTIONAL,
    value: 10,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Counselling",
    type: TaskType.OPTIONAL,
    value: 10,
    day_preference: DayPreference.DAY_RANGE,
    days: [DayOfWeek.MONDAY, DayOfWeek.SUNDAY],
    time_preference: TimePreference.ANYTIME,
  },
  {
    name: "Community Program",
    type: TaskType.OPTIONAL,
    value: 10,
    day_preference: DayPreference.DAILY,
    days: [],
    time_preference: TimePreference.ANYTIME,
  },
]