export enum BadgeIcon {
  FIVE_STAR = "fiveStar",
  FOUR_STAR = "fourStar",
  GROUP = "group",
  HEART = "heart",
  HOME = "home",
  BABY = "baby",
  WINGS = "wings",
  FLOWER = "flower",
  MONEY = "money",
  GEMSTONE = "gemstone",
  DIAMOND = "diamond",
  PENCIL = "pencil",
  TOOL = "tool",
}

export const BADGE_ICONS = [
  BadgeIcon.FIVE_STAR,
  BadgeIcon.FOUR_STAR,
  BadgeIcon.GROUP,
  BadgeIcon.HEART,
  BadgeIcon.HOME,
  BadgeIcon.BABY,
  BadgeIcon.WINGS,
  BadgeIcon.FLOWER,
  BadgeIcon.MONEY,
  BadgeIcon.GEMSTONE,
  BadgeIcon.DIAMOND,
  BadgeIcon.PENCIL,
  BadgeIcon.TOOL,
];